{% set name = "localtileserver" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3c422966a7145ddaf5131c374627ba3a863648fa38090489c856d96ccdb433c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - localtileserver = localtileserver.__main__:run_app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}
    - anywidget >=0.9
    - click
    - fastapi >=0.100.0
    - jinja2
    - jupyter-loopback >=0.3.3
    - requests
    - rio-cogeo
    - rio-tiler
    - scooby
    - server-thread
    - uvicorn-standard

test:
  imports:
    - localtileserver
  commands:
    - pip check
    - localtileserver --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/banesullivan/localtileserver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Locally serve geospatial raster tiles in the Slippy Map standard
  description: |
    Need to visualize a rather large (gigabytes+) raster locally? This is for
    you. localtileserver serves tiles from large raster files in the Slippy
    Map standard (i.e., ``/zoom/x/y.png``) for visualization in Jupyter with
    ipyleaflet or folium. Built on rio-tiler and FastAPI.
  doc_url: https://localtileserver.banesullivan.com/
  dev_url: https://github.com/banesullivan/localtileserver

extra:
  recipe-maintainers:
    - banesullivan
    - giswqs
